version: '3.3'
services:
  app:
   container_name: app
   image: artyshnamchyl85/test
  db:
   container_name: db
   image: mysql:5.7
   environment:
     - MYSQL_ROOT_PASSWORD=r00t
   volumes:
     - ./db/mysql-datadir:/var/lib/mysql
   ports:
     - "3307:3306"
